apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - thebrainsurf.site
      secretName: thebrainsurf-tls
  rules:
    - host: thebrainsurf.site
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: hello-proxy
                port:
                  number: 80
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: hello-proxy
                port:
                  number: 80
          - path: /jumbotron.css
            pathType: Exact
            backend:
              service:
                name: hello-proxy
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
